[Settings]
# M/G
gpu_mem_th = 1G

# hh:mm
usage_limit = 02:00

# hh:mm(start1)-hh:mm(end1), hh:mm(start2)-hh:mm(end2), ...
time_limits = 00:01-07:00,11:30-17:00

# log every x seconds
log_interval = 60

# starting point
starting_point = 07:00

default_keywords = GOG Games,Steam,Roblox
